// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PRJsShfaceC1z2ueOnwohJOXfnbCfYA',
    appId: '1:268319866970:android:76735f749e63e6e5f0d863',
    messagingSenderId: '268319866970',
    projectId: 'flutter-integration-test-8faf5',
    storageBucket: 'flutter-integration-test-8faf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRabUqE9EmCCwnyrVgbofJ67odXlkRkc',
    appId: '1:268319866970:ios:50daeffc60495344f0d863',
    messagingSenderId: '268319866970',
    projectId: 'flutter-integration-test-8faf5',
    storageBucket: 'flutter-integration-test-8faf5.firebasestorage.app',
    iosBundleId: 'com.lucassales.flutterIntegrationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRabUqE9EmCCwnyrVgbofJ67odXlkRkc',
    appId: '1:268319866970:ios:50daeffc60495344f0d863',
    messagingSenderId: '268319866970',
    projectId: 'flutter-integration-test-8faf5',
    storageBucket: 'flutter-integration-test-8faf5.firebasestorage.app',
    iosBundleId: 'com.lucassales.flutterIntegrationTest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4NDAfiTRngX3UdtplLrKOVjcB9irOss0',
    appId: '1:268319866970:web:eb4ed3b4d6b2c823f0d863',
    messagingSenderId: '268319866970',
    projectId: 'flutter-integration-test-8faf5',
    authDomain: 'flutter-integration-test-8faf5.firebaseapp.com',
    storageBucket: 'flutter-integration-test-8faf5.firebasestorage.app',
  );

}