default_platform(:android)

platform :android do
  desc "Get latest version code"
  lane :get_version_code do
    supply(
      package_name: ENV["ANDROID_PACKAGE_NAME"],
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

platform :ios do
  desc "Get latest build number"
  lane :get_build_number do
    latest_testflight_build_number(
      app_identifier: ENV["IOS_BUNDLE_ID"],
      api_key: app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"]
      )
    )
  end
end