platform :android do
  desc "Get next build number from Play Store"
  lane :next_build_number do
    latest = get_new_build_number(
      package_name: "com.lucassales.flutter_integration_test.dev",
      google_play_json_key_path: "/tmp/google_play.json"
    )
    next_build = latest.to_i + 1
    UI.message("Next build number: #{next_build}") # log só informativo
    return next_build.to_s # <-- o valor que será capturado
  end
end