name: Flutter E2E Tests on Release Tags

on:
  # workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-28

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Build debug APK
        run: flutter build apk --debug --flavor dev --dart-define=USE_FIREBASE_EMULATORS=true

      - name: Start emulator and run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 15
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb install build/app/outputs/flutter-apk/app-dev-debug.apk
            firebase emulators:exec "maestro test integration_test/maestro"

      - name: Upload Maestro failure artifacts (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-artifacts
          path: /home/runner/.maestro/tests/**